version: "3.8"

services:
  db:
    container_name: "${DB_NAME}_mariadb"
    image: mariadb:latest
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    container_name: "${DB_NAME}_phpmyadmin"
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    depends_on:
      - db
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: ${DB_USER_NAME}
      PMA_PASSWORD: ${DB_USER_PASSWORD}
      UPLOAD_LIMIT: 20M
    restart: always

volumes:
  db_data:
